name: martyfm
favicon: null
layout_spectrum: 0.52096
typography_spectrum: 0.011464138515293598
title: Marty Desilets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.40049303136765957
  lightness: 0.764032194390893
  saturation: 0.3508012369275093
  rhythmicContrast: 0.6354826495517045
purpose: []
